SPACE:
  NAME: 'nasbench201'
  CHANNELS: 16
  LAYERS: 5
  NODES: 4
LOADER:
  DATASET: 'cifar10'
  SPLIT: [0.8, 0.2]
  BATCH_SIZE: 256
  NUM_CLASSES: 10
SEARCH:
  IM_SIZE: 32
  EVALUATION: 'nasbench201'
OPTIM:
  STEPS: [48, 96]
  BASE_LR: 0.025
  LR_POLICY: 'cos'
SNG:
  NAME: 'DDPNAS' 
  THETA_LR: 0.01
  PRUNING: True
  PRUNING_STEP: 3
  PROB_SAMPLING: False
  UTILITY: 'log'
  UTILITY_FACTOR: 0.4
  LAMBDA: -1
  MOMENTUM: True
  GAMMA: 0.9
  SAMPLING_PER_EDGE: 1
  RANDOM_SAMPLE: True
  WARMUP_RANDOM_SAMPLE: True
  BIGMODEL_SAMPLE_PROB: 0.
  BIGMODEL_NON_PARA: 2
  EDGE_SAMPLING: False
  EDGE_SAMPLING_EPOCH: -1
OUT_DIR: 'exp/DDPNAS'
