SPACE:
  NAME: 'nasbench201'
  NODES: 4
SEARCH:
  DATASET: 'cifar10'
  DATAPATH: "data/cifar10"
  NUM_CLASSES: 10
  BATCH_SIZE: 72
DATA_LOADER:
  NUM_WORKERS: 0
TENAS:
  SUPER_TYPE: "basic"
  TRACK: True
  PRECISION: 3
  INIT: "kaiming_normal"
  REPEAT: 3
  PRUNE_NUMBER: 1
RNG_SEED: 0