SPACE:
  NAME: 'darts'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.8, 0.2]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  STEPS: [48, 96]
SNG:
  NAME: 'ASNG'
  THETA_LR: 0.1
  PRUNING: True
  PROB_SAMPLING: False
  MOMENTUM: True
  GAMMA: 0.9
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: '/userhome/project/XNAS/experiment/ASNG_test'