SPACE:
  NAME: 'darts'
  NUM_CLASSES: 10
  CHANNEL: 16
  LAYERS: 8
  NODES: 4
  BASIC_OP: None
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.8, 0.2]
  BATCH_SIZE: 256
  IM_SIZE: 32
OUT_DIR: './experiment/darts'