SPACE:
  NAME: 'darts'
  CHANNEL: 36
  LAYERS: 20
SEARCH:
  DATASET: 'cifar10'
  DATAPATH: "data/cifar10"
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
  # LOSS_FUN: 'cross_entropy'
  # EVAL_PERIOD: 1
DATA_LOADER:
  BACKEND: 'custom'
OPTIM:
  BASE_LR: 0.1
  MIN_LR: 0.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-4
  LR_POLICY: 'cos'
  # GRAD_CLIP: 5.0
DRNAS:
  UNROLLED: False
  ALPHA_LR: 6e-4
  K: 6
  REG_TYPE: "l2"
  REG_SCALE: 1e-3
OUT_DIR: "exp/drnas_cifar10"
RNG_SEED: 2