SPACE:
  NAME: 'dropnas'
  CHANNELS: 16
  LAYERS: 8
  NODES: 4
LOADER:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
SEARCH:
  IM_SIZE: 32
OPTIM:
  BASE_LR: 0.0375
  MIN_LR: 0.0015
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3.e-4
  MAX_EPOCH: 50
  LR_POLICY: 'cos'
  WARMUP_EPOCH: 0
DARTS:
  ALPHA_WEIGHT_DECAY: 0
  ALPHA_LR: 3.e-4
DROPNAS:
  DROP_RATE: 3.e-5
OUT_DIR: 'exp/dropnas'