SPACE:
  NAME: 'darts'
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 96
  IM_SIZE: 32
TRAIN:
  CUTOUT_LENGTH: 0
OPTIM:
  BASE_LR: 0.0375
  MIN_LR: 0.0015
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0003
  MAX_EPOCH: 50
  LR_POLICY: 'cos'
DROPNAS:
  ALPHA_WEIGHT_DECAY: 0
  ALPHA_LR: 0.0003
  WARMUP_EPOCHS: 0
  DROP_RATE: 0.00003
OUT_DIR: '/userhome/project/XNAS/experiment/dropnas'