SPACE:
  NAME: 'darts'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  BASE_LR: 0.1
  MOMENTUM: 0.9
  STEPS: [60, 120]
  LR_POLICY: 'step'
  WARMUP_EPOCHS: 0
  MAX_EPOCH: 200
  FINAL_EPOCH: 50
SNG:
  NAME: 'MIGO'
  THETA_LR: 0.1
  PRUNING: False
  PROB_SAMPLING: True
  UTILITY: 'log'
  UTILITY_FACTOR: 0.4
  MOMENTUM: True
  GAMMA: 0.5
  PRUNING_STEP: 2
  BIGMODEL_SAMPLE_PROB: 0.5
  BIGMODEL_NON_PARA: 2
  EDGE_SAMPLING: True
  EDGE_SAMPLING_EPOCH: -1
  RANDOM_SAMPLE: True
  WARMUP_RANDOM_SAMPLE: True
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: '/userhome/project/XNAS/experiment/MIGO_test'