SPACE:
  NAME: 'darts'
  NUM_CLASSES: 10
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.9, 0.1]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  BASE_LR: 0.5
  MOMENTUM: 0.9
  STEPS: [60, 120]
  LR_POLICY: 'step'
  WARMUP_EPOCHS: 10
  MAX_EPOCH: 400
SNG:
  NAME: 'MIGO'
  THETA_LR: 0.1
  PRUNING: True
  PROB_SAMPLING: False
  UTILITY: 'log'
  UTILITY_FACTOR: 0.4
  MOMENTUM: True
  GAMMA: 0.5
  PRUNING_STEP: 5
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: '/userhome/project/XNAS/experiment/MIGO_test'