SPACE:
  NAME: 'nasbench1shot1_1'
  NUM_CLASSES: 10
  CHANNEL: 16
  LAYERS: 5
  NODES: 4
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  MAX_EPOCH: 50
OUT_DIR: 'experiment/nasbench1shot1'
SNG:
  NAME: 'SNG'
  RANDOM_SAMPLE: False