SPACE:
  NAME: 'pcdarts'
  CHANNELS: 16
  LAYERS: 8
  NODES: 4
LOADER:
  DATASET: 'cifar10'
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 256
  NUM_CLASSES: 10
SEARCH:
  IM_SIZE: 32
OPTIM:
  MAX_EPOCH: 50
  LR_POLICY: 'cos'
  WEIGHT_DECAY: 3e-4
  MIN_LR: 0.0
DARTS:
  UNROLLED: True
  ALPHA_LR: 6.e-4
  ALPHA_WEIGHT_DECAY: 1.e-3
OUT_DIR: 'exp/pcdarts'