SPACE:
  NAME: 'pcdarts'
  NUM_CLASSES: 10
  CHANNEL: 16
  LAYERS: 8
  NODES: 4
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
  IM_SIZE: 32
  EVAL_PERIOD: 50
OPTIM:
  MAX_EPOCH: 50
OUT_DIR: '/userhome/XNAS/experiment/pcdarts'