SPACE:
  NAME: 'spos'
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
  IM_SIZE: [32]
SPOS:
  NUMCHOICE: 4
OUT_DIR: 'username/project/XNAS/experiment/spos'