SPACE:
  NAME: 'spos_nb201'
  CHANNELS: 16
  LAYERS: 5
  NODES: 4
LOADER:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  # SPLIT: [0.5, 0.5]
  BATCH_SIZE: 128
SEARCH:
  IM_SIZE: 32
  AUTO_RESUME: False
SPOS:
  RESIZE: True
  LAYERS: 90 # 6 * 15
  NUM_CHOICE: 5
OPTIM:
  BASE_LR: 0.025
  MIN_LR: 0.001
  WEIGHT_DECAY: 1.e-4
  LR_POLICY: 'cos'
  MAX_EPOCH: 50
OUT_DIR: 'exp/spos_201'