SPACE:
  NAME: 'darts'
  CHANNEL: 48
  LAYERS: 14
SEARCH:
  DATASET: 'imagenet'
  DATAPATH: "data/imagenet"
  NUM_CLASSES: 1000
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 512
  LOSS_FUN: 'cross_entropy'
  EVAL_PERIOD: 1
DATA_LOADER:
  BACKEND: 'custom'
  NUM_WORKERS: 16
OPTIM:
  BASE_LR: 0.5
  MIN_LR: 0.0
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-4
  LR_POLICY: 'cos'
  GRAD_CLIP: 5.0
  WARMUP_EPOCHS: 10
DRNAS:
  UNROLLED: False
  ALPHA_LR: 6e-3
  ALPHA_WEIGHT_DECAY: 1e-3
  K: 6
  REG_TYPE: "l2"
  REG_SCALE: 1e-3
OUT_DIR: "exp/drnas_img"
RNG_SEED: 0