SPACE:
  NAME: 'drnas_darts'
  CHANNELS: 36
  LAYERS: 20
  NODES: 4
LOADER:
  DATASET: 'cifar10'
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 64
  NUM_CLASSES: 10
SEARCH:
  IM_SIZE: 32
OPTIM:
  MIN_LR: 0.0
  WEIGHT_DECAY: 3.e-4
  LR_POLICY: 'cos'
DARTS:
  UNROLLED: True
  ALPHA_LR: 6.e-4
  ALPHA_WEIGHT_DECAY: 1.e-3
DRNAS:
  K: 6
  REG_TYPE: "l2"
  REG_SCALE: 1.e-3
  METHOD: 'dirichlet'
  TAU: [1, 10]
OUT_DIR: 'exp/drnas'
