SPACE:
  NAME: 'nasbench201'
  CHANNEL: 16
  LAYERS: 5
  NODES: 4
SEARCH:
  DATASET: 'cifar10'
  DATAPATH: "data/cifar10"
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  LOSS_FUN: "cross_entropy"
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 4
OPTIM:
  BASE_LR: 0.025
  MIN_LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-4
  GRAD_CLIP: 5.0
  MAX_EPOCH: 100
DRNAS:
  UNROLLED: False
  METHOD: 'gdas'
  TAU: [1, 10]
RNG_SEED: 2