SPACE:
  NAME: 'nasbench201'
  CHANNEL: 16
  LAYERS: 5
  NODES: 4
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  LOSS_FUN: "cross_entropy"
DRNAS:
  K: 1
  REG_TYPE: "l2" # can be "kl" for Dirichlet
  REG_SCALE: 1e-3