RNG_SEED: 2
SEARCH:
  DATASET: 'imagenet'
  NUM_CLASSES: 1000
  IM_SIZE: 32
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/train_test'
OPTIM:
  BASE_LR: 0.025
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0003
  MAX_EPOCH: 250
TRAIN:
  BATCH_SIZE: 32
  CHANNELS: 16
  LAYERS: 8