RNG_SEED: 7
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/nb201_train'
OPTIM:
  BASE_LR: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005
  MAX_EPOCH: 150
TRAIN:
  BATCH_SIZE: 32
  CHECKPOINT_PERIOD: 10