SPACE:
  NAME: 'mobilenetV3'
LOADER:
  DATASET: 'imagenet'
  NUM_CLASSES: 10
  NUM_WORKERS: 0
  BATCH_SIZE: 128
OPTIM:
  BASE_LR: 0.025
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0003
  MAX_EPOCH: 350
TRAIN:
  CHANNELS: 16
  LAYERS: 8
RMINAS:
  LOSS_BETA: 0.8
  RF_WARMUP: 100
  RF_THRESRATE: 0.05
  RF_SUCC: 100
OUT_DIR: 'exp/rminas'