SPACE:
  NAME: 'infer_darts'
LOADER:
  DATASET: 'cifar10'
  BATCH_SIZE: 96
  NUM_CLASSES: 10
TEST:
  BATCH_SIZE: 96  # stay same.
OPTIM:
  BASE_LR: 0.025
  WEIGHT_DECAY: 3.e-4
  MAX_EPOCH: 600
TRAIN:
  CHANNELS: 36
  LAYERS: 20
  AUX_WEIGHT: 0.4
  DROP_PATH_PROB: 0.3
  GENOTYPE: "Genotype(normal=[('sep_conv_5x5', 1), ('sep_conv_3x3', 0),('skip_connect', 0), ('sep_conv_5x5', 1),('sep_conv_5x5', 3), ('sep_conv_3x3', 1),('dil_conv_5x5', 3), ('max_pool_3x3', 4)], normal_concat=range(2, 6), reduce=[('max_pool_3x3', 0), ('sep_conv_5x5', 1),('skip_connect', 0), ('skip_connect', 1),('sep_conv_3x3', 3), ('skip_connect', 2),('dil_conv_3x3', 3), ('sep_conv_5x5', 0)], reduce_concat=range(2, 6))"