DATA_LOADER:
  BACKEND: 'custom'
OUT_DIR: 'experiment/train_test'
TRAIN:
  DATASET: 'cifar10'
  SPLIT: [0.8, 0.2]
  BATCH_SIZE: 96
  GENOTYPE: "Genotype(normal=[[('sep_conv_5x5', 1), ('sep_conv_3x3', 0)],[('skip_connect', 0), ('sep_conv_5x5', 1)],[('sep_conv_5x5', 3), ('sep_conv_3x3', 1)],[('dil_conv_5x5', 3), ('max_pool_3x3', 4)],], normal_concat=range(2, 6), reduce=[[('max_pool_3x3', 0), ('sep_conv_5x5', 1)],[('skip_connect', 0), ('skip_connect', 1)],[('sep_conv_3x3', 3), ('skip_connect', 2)],[('dil_conv_3x3', 3), ('sep_conv_5x5', 0)],], reduce_concat=range(2, 6))"