SPACE:
  NAME: 'nasbench201'
  CHANNEL: 16
  LAYERS: 5
  NODES: 4
DATA_LOADER:
  BACKEND: 'custom'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 256
  IM_SIZE: 32
OPTIM:
  MAX_EPOCH: 50
OUT_DIR: '/userhome/project/XNAS/experiment/nasbench201/test'