# OUT_DIR: '/userhome/project/XNAS/experiment/OFA/mbv3_cifar10/expand/phase2'
OUT_DIR: '/home/binghan/XNAS/experiment/OFA/mbv3_cifar10/expand/phase2'
NUM_GPUS: 1
SPACE:
  NAME: 'ofa_mbv3'
DATA_LOADER:
  BACKEND: 'torch'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 1024
  IM_SIZE: [128,160,192,224]
  LOSS_FUN: 'cross_entropy_with_label_smoothing'
  LABEL_SMOOTH: 0.1
  # DATAPATH: 'TODO'
  DATAPATH: './data/cifar10'
  # WEIGHTS: '//userhome/project/XNAS/experiment/OFA/mbv3_cifar10/expand/phase1/checkpoints/model_epoch_0025.pyth'
  WEIGHTS: '/home/binghan/XNAS/experiment/OFA/mbv3_cifar10/expand/phase1/checkpoints/model_epoch_0025.pyth'
  AUTO_RESUME: True
OFA:
  TASK: 'expand'
  PHASE: 2
  WIDTH_MULTI_LIST: [1.0]
  KS_LIST: [3,5,7]
  EXPAND_LIST: [3,4,6]
  DEPTH_LIST: [2,3,4]
OPTIM:
  MAX_EPOCH: 120
  BASE_LR: 7.5e-3
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.2
  LR_POLICY: 'cos'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-5
TEST:
  BATCH_SIZE: 1024
  IM_SIZE: 224

