# OUT_DIR: '/userhome/project/XNAS/experiment/OFA/mbv3_cifar10/normal/phase1'
OUT_DIR: '/home/binghan/XNAS/experiment/OFA/mbv3_cifar10/normal/phase1'
NUM_GPUS: 1
SPACE:
  NAME: 'ofa_mbv3'
SEARCH:
  DATASET: 'cifar10'
  NUM_CLASSES: 10
  SPLIT: [0.5, 0.5]
  BATCH_SIZE: 1024
  MULTI_SIZES: [128,160,192,224]
  LOSS_FUN: 'cross_entropy_with_label_smoothing'
  LABEL_SMOOTH: 0.1
  # DATAPATH: 'TODO'
  DATAPATH: './data/cifar10'
  # WEIGHTS: 'TODO'
  WEIGHTS: ''
  AUTO_RESUME: True
OFA:
  TASK: 'normal'
  PHASE: 1
  WIDTH_MULTI_LIST: [1.0]
  KS_LIST: [7]
  EXPAND_LIST: [6]
  DEPTH_LIST: [4]
  CHANNEL_DIVISIBLE: 8
OPTIM:
  MAX_EPOCH: 180
  BASE_LR: 0.1625
  WARMUP_EPOCH: 5
  WARMUP_FACTOR: 0.2
  LR_POLICY: 'cos'
  MOMENTUM: 0.9
  WEIGHT_DECAY: 3e-5
  OPTIM.NESTEROV: True
TEST:
  BATCH_SIZE: 1024
  IM_SIZE: 224

